// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.5.3 avatar.glb -T 
// Files: avatar.glb [1.25MB] > D:\Portfolio\3d\laibae-awan\public\models\avatar-transformed.glb [641.35KB] (49%)
// */
// "use client";

// import React, { useEffect, useRef } from "react";
// import { useGraph } from "@react-three/fiber";
// import { useGLTF } from "@react-three/drei";
// import { SkeletonUtils } from "three-stdlib";
// import * as THREE from "three";
// import { useGSAP } from "@gsap/react";
// import gsap from "gsap";
// import { ScrollTrigger } from "gsap/ScrollTrigger";

// gsap.registerPlugin(ScrollTrigger);

// export function Avatar(props: any) {
//   const { scene } = useGLTF("/models/avatar-transformed.glb");
//   const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
//   const { nodes, materials } = useGraph(clone);

//   const group = useRef();
//   const mouse = useRef(new THREE.Vector2());
//   const [isIntroAnimationDone, setIsIntroAnimationDone] = React.useState(false);

//   const isMobile = useRef(false);

//   useEffect(() => {
//     isMobile.current = window.innerWidth < 768;
//   }, []);

//   useGSAP(() => {
//     if (!isIntroAnimationDone) {
//       gsap.fromTo(
//         group.current.rotation,
//         { y: Math.PI },
//         {
//           y: 0.2,
//           delay: 0.5,
//           duration: 1.5,
//           ease: "expo.inOut",
//           onComplete: () => setIsIntroAnimationDone(true),
//         },
//       );
//     }

//     if (isIntroAnimationDone) {
//       // 🎯 Scroll-based movement
//       gsap.to(group.current.position, {
//         y: 3, // how far up it moves
//         scrollTrigger: {
//           trigger: "#scroll-container", // 👈 set your scroll container ID
//           start: "top top",
//           end: "bottom bottom",
//           scrub: true,
//         },
//       });

//       // 🐭 Mouse look
//       const handleMouseMove = (event) => {
//         const { innerWidth, innerHeight } = window;
//         mouse.current.x = (event.clientX / innerWidth) * 2 - 1;
//         mouse.current.y = -(event.clientY / innerHeight) * 2 + 1;

//         const target = new THREE.Vector3(mouse.current.x, mouse.current.y, 3);
//         group.current.rotation.y = target.x * 0.5;
//         group.current.getObjectByName("Head")?.lookAt(target);
//       };

//       if (!isMobile.current) {
//         window.addEventListener("mousemove", handleMouseMove);
//       }
//       return () => window.removeEventListener("mousemove", handleMouseMove);
//     }
//   }, [isIntroAnimationDone]);

//   return (
//     <group ref={group} {...props} dispose={null}>
//       <primitive object={nodes.Hips} />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Hair.geometry}
//         material={materials.Wolf3D_Hair}
//         skeleton={nodes.Wolf3D_Hair.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Glasses.geometry}
//         material={materials.Wolf3D_Glasses}
//         skeleton={nodes.Wolf3D_Glasses.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Body.geometry}
//         material={materials.Wolf3D_Body}
//         skeleton={nodes.Wolf3D_Body.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
//         material={materials.Wolf3D_Outfit_Bottom}
//         skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
//         material={materials.Wolf3D_Outfit_Footwear}
//         skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
//       />
//       <skinnedMesh
//         geometry={nodes.Wolf3D_Outfit_Top.geometry}
//         material={materials.Wolf3D_Outfit_Top}
//         skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
//       />
//       <skinnedMesh
//         name="EyeLeft"
//         geometry={nodes.EyeLeft.geometry}
//         material={materials.Wolf3D_Eye}
//         skeleton={nodes.EyeLeft.skeleton}
//         morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="EyeRight"
//         geometry={nodes.EyeRight.geometry}
//         material={materials.Wolf3D_Eye}
//         skeleton={nodes.EyeRight.skeleton}
//         morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
//         morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Head"
//         geometry={nodes.Wolf3D_Head.geometry}
//         material={materials.Wolf3D_Skin}
//         skeleton={nodes.Wolf3D_Head.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
//       />
//       <skinnedMesh
//         name="Wolf3D_Teeth"
//         geometry={nodes.Wolf3D_Teeth.geometry}
//         material={materials.Wolf3D_Teeth}
//         skeleton={nodes.Wolf3D_Teeth.skeleton}
//         morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
//         morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
//       />
//     </group>
//   );
// }

// useGLTF.preload("/models/avatar-transformed.glb");

"use client"

import React, { useEffect, useMemo, useRef, useState } from "react"
import { useGraph } from "@react-three/fiber"
import { useGLTF } from "@react-three/drei"
import { SkeletonUtils } from "three-stdlib"
import * as THREE from "three"
import { useGSAP } from "@gsap/react"
import gsap from "gsap"
import { ScrollTrigger } from "gsap/ScrollTrigger"

gsap.registerPlugin(ScrollTrigger)

type AvatarProps = React.ComponentProps<"group">


export function Avatar(props: AvatarProps) {
  const { scene } = useGLTF("/models/avatar-transformed.glb")

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])

  const { nodes, materials } = useGraph(clone) as any
  // gltfjsx types are complex — casting avoids strict build issues safely

  const group = useRef<THREE.Group | null>(null)
  const mouse = useRef<THREE.Vector2>(new THREE.Vector2())
  const isMobile = useRef<boolean>(false)

  const [isIntroAnimationDone, setIsIntroAnimationDone] =
    useState<boolean>(false)

  useEffect(() => {
    isMobile.current = window.innerWidth < 768
  }, [])

  useGSAP(
    () => {
      if (!group.current) return

      // 🎬 Intro rotation animation
      if (!isIntroAnimationDone) {
        gsap.fromTo(
          group.current.rotation,
          { y: Math.PI },
          {
            y: 0.2,
            delay: 0.5,
            duration: 1.5,
            ease: "expo.inOut",
            onComplete: () => setIsIntroAnimationDone(true),
          }
        )
      }

      // 🎯 Scroll movement
      if (isIntroAnimationDone) {
        gsap.to(group.current.position, {
          y: 3,
          scrollTrigger: {
            trigger: "#scroll-container",
            start: "top top",
            end: "bottom bottom",
            scrub: true,
          },
        })
      }

      // 🐭 Mouse look
      const handleMouseMove = (event: MouseEvent) => {
        if (!group.current) return

        const { innerWidth, innerHeight } = window

        mouse.current.x = (event.clientX / innerWidth) * 2 - 1
        mouse.current.y = -(event.clientY / innerHeight) * 2 + 1

        const target = new THREE.Vector3(
          mouse.current.x,
          mouse.current.y,
          3
        )

        group.current.rotation.y = target.x * 0.5

        const head = group.current.getObjectByName("Head")
        if (head) {
          ;(head as THREE.Object3D).lookAt(target)
        }
      }

      if (!isMobile.current) {
        window.addEventListener("mousemove", handleMouseMove)
      }

      return () => {
        window.removeEventListener("mousemove", handleMouseMove)
      }
    },
    { dependencies: [isIntroAnimationDone] }
  )

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />

      <skinnedMesh
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
        skeleton={nodes.Wolf3D_Hair.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
        skeleton={nodes.Wolf3D_Glasses.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
        skeleton={nodes.Wolf3D_Body.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
        skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
        skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
        skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
      />

      <skinnedMesh
        name="EyeLeft"
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeLeft.skeleton}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />

      <skinnedMesh
        name="EyeRight"
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        skeleton={nodes.EyeRight.skeleton}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />

      <skinnedMesh
        name="Wolf3D_Head"
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        skeleton={nodes.Wolf3D_Head.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />

      <skinnedMesh
        name="Wolf3D_Teeth"
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        skeleton={nodes.Wolf3D_Teeth.skeleton}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  )
}

useGLTF.preload("/models/avatar-transformed.glb")
